language: node_js
sudo: required
cache: false
os:
  - linux
  - osx
node_js:
  - "12.7.0"

services:
  - xvfb

addons:
  chrome: stable
  firefox: latest

stages:
  - install
  - build
  - build size
  - code format
  - checks

jobs:
  include:
    - stage: install
      script: travis_retry npm install --depth 0 --silent
    
    - stage: build
      script: npm run build
    
    - stage: build size
      script: npm run size:webpack
      env: LABEL=size:webpack
    - stage: build size
      script: npm run size:browserify
      env: LABEL=size:browserify
    - stage: build size
      script: npm run size:rollup
      env: LABEL=size:rollup

    - stage: code format
      script: npm run lint
      env: LABEL=lint
    - stage: code format
      script: npm run test:typings
      env: LABEL=test:typings

    - stage: checks
      script: npm run test:node
      env: LABEL=test:node
    - stage: checks
      script: if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ( travis_retry npm run test:browser ) fi
      env: LABEL=test:browser
    - stage: checks
      script: travis_retry npm run test:performance
      env: LABEL=run test:performance
    - stage: checks
      script: if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ( sleep 10 && travis_retry npm run test:e2e:travis ) fi
      env: LABEL=test:e2e